/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governanceDaoSol from "./GovernanceDAO.sol";
export type { governanceDaoSol };
import type * as propertyTokenFactorySol from "./PropertyTokenFactory.sol";
export type { propertyTokenFactorySol };
export type { Marketplace } from "./Marketplace";
export type { PropertyNFT } from "./PropertyNFT";
export type { PropertyToken } from "./PropertyToken";
export type { SyntiantToken } from "./SyntiantToken";
