/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPropertyNFT__factory } from "./IPropertyNFT__factory";
export { PropertyTokenFactory__factory } from "./PropertyTokenFactory__factory";
