/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPropertyTokenFactory,
  IPropertyTokenFactoryInterface,
} from "../../../contracts/GovernanceDAO.sol/IPropertyTokenFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "propertyId",
        type: "uint256",
      },
    ],
    name: "propertyTokens",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPropertyTokenFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IPropertyTokenFactoryInterface {
    return new Interface(_abi) as IPropertyTokenFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPropertyTokenFactory {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPropertyTokenFactory;
  }
}
