/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPropertyNFT } from "./IPropertyNFT";
export type { PropertyTokenFactory } from "./PropertyTokenFactory";
