/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IPropertyNFTInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getFundingTarget"
      | "getMinInvestment"
      | "getPropertyStatus"
      | "updatePropertyStatus"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getFundingTarget",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinInvestment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPropertyStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePropertyStatus",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getFundingTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPropertyStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePropertyStatus",
    data: BytesLike
  ): Result;
}

export interface IPropertyNFT extends BaseContract {
  connect(runner?: ContractRunner | null): IPropertyNFT;
  waitForDeployment(): Promise<this>;

  interface: IPropertyNFTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFundingTarget: TypedContractMethod<
    [propertyId: BigNumberish],
    [bigint],
    "view"
  >;

  getMinInvestment: TypedContractMethod<
    [propertyId: BigNumberish],
    [bigint],
    "view"
  >;

  getPropertyStatus: TypedContractMethod<
    [propertyId: BigNumberish],
    [bigint],
    "view"
  >;

  updatePropertyStatus: TypedContractMethod<
    [propertyId: BigNumberish, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getFundingTarget"
  ): TypedContractMethod<[propertyId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMinInvestment"
  ): TypedContractMethod<[propertyId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPropertyStatus"
  ): TypedContractMethod<[propertyId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "updatePropertyStatus"
  ): TypedContractMethod<
    [propertyId: BigNumberish, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
