/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace PropertyTokenFactory {
  export type InvestmentRecordStruct = {
    investor: AddressLike;
    amount: BigNumberish;
    shares: BigNumberish;
    timestamp: BigNumberish;
  };

  export type InvestmentRecordStructOutput = [
    investor: string,
    amount: bigint,
    shares: bigint,
    timestamp: bigint
  ] & { investor: string; amount: bigint; shares: bigint; timestamp: bigint };
}

export interface PropertyTokenFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "TOTAL_SHARES_PER_PROPERTY"
      | "createPropertyToken"
      | "getInvestorShares"
      | "getPropertyInvestments"
      | "getPropertyToken"
      | "invest"
      | "investorShares"
      | "owner"
      | "propertyInvestments"
      | "propertyNFT"
      | "propertyTokens"
      | "renounceOwnership"
      | "syntiantToken"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "InvestmentMade"
      | "OwnershipTransferred"
      | "PropertyTokenCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "TOTAL_SHARES_PER_PROPERTY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createPropertyToken",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvestorShares",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPropertyInvestments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPropertyToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "invest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "investorShares",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "propertyInvestments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "propertyNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "propertyTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "syntiantToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "TOTAL_SHARES_PER_PROPERTY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPropertyToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInvestorShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPropertyInvestments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPropertyToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "invest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "investorShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "propertyInvestments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "propertyNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "propertyTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "syntiantToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace InvestmentMadeEvent {
  export type InputTuple = [
    propertyId: BigNumberish,
    investor: AddressLike,
    amount: BigNumberish,
    shares: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: bigint,
    investor: string,
    amount: bigint,
    shares: bigint
  ];
  export interface OutputObject {
    propertyId: bigint;
    investor: string;
    amount: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PropertyTokenCreatedEvent {
  export type InputTuple = [
    propertyId: BigNumberish,
    tokenAddress: AddressLike
  ];
  export type OutputTuple = [propertyId: bigint, tokenAddress: string];
  export interface OutputObject {
    propertyId: bigint;
    tokenAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PropertyTokenFactory extends BaseContract {
  connect(runner?: ContractRunner | null): PropertyTokenFactory;
  waitForDeployment(): Promise<this>;

  interface: PropertyTokenFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  TOTAL_SHARES_PER_PROPERTY: TypedContractMethod<[], [bigint], "view">;

  createPropertyToken: TypedContractMethod<
    [propertyId: BigNumberish, name: string, symbol: string],
    [void],
    "nonpayable"
  >;

  getInvestorShares: TypedContractMethod<
    [propertyId: BigNumberish, investor: AddressLike],
    [bigint],
    "view"
  >;

  getPropertyInvestments: TypedContractMethod<
    [propertyId: BigNumberish],
    [PropertyTokenFactory.InvestmentRecordStructOutput[]],
    "view"
  >;

  getPropertyToken: TypedContractMethod<
    [propertyId: BigNumberish],
    [string],
    "view"
  >;

  invest: TypedContractMethod<
    [propertyId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  investorShares: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  propertyInvestments: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  propertyNFT: TypedContractMethod<[], [string], "view">;

  propertyTokens: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  syntiantToken: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "TOTAL_SHARES_PER_PROPERTY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createPropertyToken"
  ): TypedContractMethod<
    [propertyId: BigNumberish, name: string, symbol: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getInvestorShares"
  ): TypedContractMethod<
    [propertyId: BigNumberish, investor: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPropertyInvestments"
  ): TypedContractMethod<
    [propertyId: BigNumberish],
    [PropertyTokenFactory.InvestmentRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPropertyToken"
  ): TypedContractMethod<[propertyId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "invest"
  ): TypedContractMethod<
    [propertyId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "investorShares"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "propertyInvestments"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "propertyNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "propertyTokens"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "syntiantToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "InvestmentMade"
  ): TypedContractEvent<
    InvestmentMadeEvent.InputTuple,
    InvestmentMadeEvent.OutputTuple,
    InvestmentMadeEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PropertyTokenCreated"
  ): TypedContractEvent<
    PropertyTokenCreatedEvent.InputTuple,
    PropertyTokenCreatedEvent.OutputTuple,
    PropertyTokenCreatedEvent.OutputObject
  >;

  filters: {
    "InvestmentMade(uint256,address,uint256,uint256)": TypedContractEvent<
      InvestmentMadeEvent.InputTuple,
      InvestmentMadeEvent.OutputTuple,
      InvestmentMadeEvent.OutputObject
    >;
    InvestmentMade: TypedContractEvent<
      InvestmentMadeEvent.InputTuple,
      InvestmentMadeEvent.OutputTuple,
      InvestmentMadeEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PropertyTokenCreated(uint256,address)": TypedContractEvent<
      PropertyTokenCreatedEvent.InputTuple,
      PropertyTokenCreatedEvent.OutputTuple,
      PropertyTokenCreatedEvent.OutputObject
    >;
    PropertyTokenCreated: TypedContractEvent<
      PropertyTokenCreatedEvent.InputTuple,
      PropertyTokenCreatedEvent.OutputTuple,
      PropertyTokenCreatedEvent.OutputObject
    >;
  };
}
